msviz-frontend:
  image: eboraas/apache
  ports:
  - "9001:80"
  volumes:
  - ./msviz-frontend/htdocs:/var/www/html
  links:
  - msviz-backend
  mem_limit: 4g
msviz-backend:
  build: ./msviz-backend
  ports:
  - "9000:9000"
  links:
  - mongodb:mongo-msviz
  mem_limit: 1g
mongodb:
  image: mongo
  ports:
  - "27017:27017"
  mem_limit: 2g
